### ISSUE TITLE
Use babel-plugin-ramda v1.5.0

### ISSUE THREAD

**Issue by jogold** [goldwasserexchange/javascript#9]
Replace `babel-plugin-transform-imports` by `babel-plugin-ramda` v1.5.0 now that it supports the `es` path. See https://github.com/megawac/babel-plugin-ramda/pull/34

**Comment by belgac** [comment]
Shouldn't we keep the `babel-plugin-transform-imports` for goldwasserexchange/utils and react-router and add the `babel-plugin-ramda` only for ramda?

**Comment by jogold** [comment]
Yes
